### ISSUE TITLE
Empty spaces on long devices 

### ISSUE THREAD

**Issue by iqfareez** [iqfareez/App-Waktu-Solat-Malaysia#13]
![image](https://user-images.githubusercontent.com/60868965/93617682-de087500-fa08-11ea-9c20-d95a29cd3211.png)

Might consider to dynamically resize the header or the card

_Reported by Naufal_

**Comment by fareezMaple** [comment]
Will add setting to adjust size / space

**Comment by iqfareez** [comment]
Idk seem like it is not the issue anymore. Feel free to reopen together with your screenshot.
