### ISSUE TITLE
Wrong Zohor time

### ISSUE THREAD

**Issue by butitik** [iqfareez/App-Waktu-Solat-Malaysia#49]
**Describe the bug**
When i updated the app to the latest version yesterday, it seems that the Zohor prayer time for Tuaran, Sabah (SBH07) has been set to work on the wrong end of the time scale (eg. 12.00AM when it's supposed to be 12.00PM)

**To Reproduce**
1. Go to app
2. See error

**Expected behavior**
Zohor time is expected on 12.33PM with notification on.

**Screenshots**
![Screenshot_2021-02-18-12-52-07-63_7982d9b9309ab0857893468fdfeab7f5](https://user-images.githubusercontent.com/79241882/108307600-029b8f80-71e9-11eb-8f1f-65e147c9312e.jpg)

**Debug Info:**
None.
-------------

-------------

**Additional context**
Have tried both refreshing the location choice settings in the app and restarting the app itself, still to the same result.

**Comment by iqfareez** [comment]
Thank you for submitting bug report & and sorry for any inconvenience. I'll investigate this issue asap.
